names:
  numberFormat: "_{num:02}"
  keywords:
    general:
      - world
      - root
      - main
      - pelvis
      - spine
      - torso
      - chest
    arms:
      - clavicle
      - shoulder
      - elbow
      - upperarm
      - lowerarm
      - hand
      - wrist
      - index
      - middle
      - ring
      - pinky
      - thumb
    legs:
      - hip
      - leg
      - knee
      - thigh
      - calf
      - foot
      - ankle
      - heel
      - ball
      - toe
      - toes
    head:
      - head
      - eye
      - eyes
      - ear
      - nose
      - mouth
      - hair
      - jaw
      - teeth
      - tongue
      - cheek
  prefixes: [ ]
  suffixes:
    - name: ik
      sort: 7
    - name: twist
      sort: 8
    - name: sub
      sort: 9
    - name: base
      sort: 10
    - name: lift
      sort: 11
    - name: space
      sort: 50
    - name: pivot
      sort: 51
    - name: mid
      sort: 100
    - name: end
      sort: 101
    - name: top
      sort: 102
    - name: bot
      sort: 103
    - name: f
      sort: 104
    - name: b
      sort: 105
    - name: c
      sort: 106
    - name: l
      sort: 107
    - name: r
      sort: 108
    - name: jnt
      sort: 200
    - name: ctl
      sort: 201
    - name: grp
      sort: 202
colors:
  root: "#f6bd15"
  main_c: "#f6bd15"
  alt_c: "#594407"
  main_l: "#186fd5"
  main_r: "#832121"
symmetry:
  pairs:
    - left: l
      right: r
    - left: L
      right: R
    - left: left
      right: right
    - left: Left
      right: Right
default_blueprint:
  steps:
    children:
      - action:
          id: Pulse.RenameScene
      - action:
          id: Pulse.ImportReferences
      - action:
          id: Pulse.CreateRig
      - action:
          id: Pulse.BuildCoreHierarchy
          variantAttrs:
            - groupName
            - allNodes
            - nodes
          variants:
            - groupName: core
            - allNodes: true
              groupName: ctls
      - name: Main
      - action:
          id: Pulse.SetAttributeDefaults
    name: Root
