names:
  numberFormat: "_{num:02}"
  keywords:
    general:
    - world
    - root
    - main
    - pelvis
    - spine
    - torso
    - chest
    arms:
    - clavicle
    - shoulder
    - elbow
    - upperarm
    - lowerarm
    - hand
    - wrist
    - pointfinger
    - middlefinger
    - ringfinger
    - pinky
    - thumb
    legs:
    - hip
    - leg
    - knee
    - thigh
    - calf
    - foot
    - toe
    - toes
    - ankle
    - ball
    head:
    - head
    - eye
    - eyes
    - ear
    - nose
    - mouth
    - hair
    - jaw
    - teeth
    - tongue
    - cheek
  prefixes: {}
  suffixes:
  - name: jnt
    sort: 10
  - name: ctl
    sort: 10
  - name: sub
    sort: 9
  - name: twist
    sort: 8
  - name: ik
    sort: 7
  - name: mid
    sort: 6
  - name: end
    sort: 6
  - name: top
    sort: 100
  - name: bot
    sort: 100
  - name: f
    sort: 101
  - name: b
    sort: 101
  - name: c
    sort: 102
  - name: l
    sort: 103
  - name: r
    sort: 103
colors:
  - name: root
    color: "#f6bd15"
  - name: c_main
    color: "#f6bd15"
  - name: c_alt
    color: "#594407"
  - name: l_main
    color: "#186fd5"
  - name: r_main
    color: "#832121"
symmetry:
  pairs:
    - left: l
      right: r
    - left: L
      right: R
    - left: left
      right: right
    - left: Left
      right: Right
