mv constraints/aimconstrain_pulseaction.py constraints/aimconstrain.py
mv constraints/matrixconstrain_pulseaction.py constraints/matrixconstrain.py
mv constraints/parent_pulseaction.py constraints/parent.py
mv constraints/simple_constrain_pulseaction.py constraints/simple_constrain.py
mv constraints/spaces_pulseaction.py constraints/spaces.py
mv controls/anim_control_pulseaction.py controls/anim_control.py
mv controls/foot_control_pulseaction.py controls/foot_control.py
mv controls/magic_feet_pulseaction.py controls/magic_feet.py
mv controls/magic_hands_pulseaction.py controls/magic_hands.py
mv controls/set_attribute_defaults_pulseaction.py controls/set_attribute_defaults.py
mv core/core_hierarchy_pulseaction.py core/core_hierarchy.py
mv core/import_references_pulseaction.py core/import_references.py
mv core/optimize_scene_pulseaction.py core/optimize_scene.py
mv core/rename_scene_pulseaction.py core/rename_scene.py
mv deformers/bind_skin_pulseaction.py deformers/bind_skin.py
mv joints/cleanup_joints_pulseaction.py joints/cleanup_joints.py
mv joints/twist_joints_pulseaction.py joints/twist_joints.py
mv kinematics/addikfk_control_pulseaction.py kinematics/addikfk_control.py
mv kinematics/ikfk_pulseaction.py kinematics/ikfk.py
mv organization/display_layer_pulseaction.py organization/display_layer.py
mv organization/object_set_pulseaction.py organization/object_set.py
